### ISSUE TITLE
ERROR #429

### ISSUE THREAD

**Issue by Maxwell999b** [ahmad-kashkoush/Hotel-management-system#1]
# Error Across the whole Site 👍 :
Almost Everything Naming few Here 👇 :
- [Bookings](https://hotel-management-system-mu.vercel.app/bookings)
- [Cabins](https://hotel-management-system-mu.vercel.app/cabins)
- [Users](https://hotel-management-system-mu.vercel.app/users)
- [Settings](https://hotel-management-system-mu.vercel.app/settings)
- [User Profile Icon]()
the Error Deatails : 
```md
# something went wrong
Minified React error #426; visit https://reactjs.org/docs/error-decoder.html?invariant=426 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```
ss ⬇️ :
![image](https://github.com/user-attachments/assets/a057baa7-bb7d-41c1-a30d-23494d0aa9fd)

Thoughts about Try to Fix the Issue : 
- try to test the Website on :New Incognito Tab 
> to test without the Saved Locally data on the User.

**Comment by ahmad-kashkoush** [comment]
Thanks, I'll fix it

**Comment by ahmad-kashkoush** [comment]
I've solved it, thanks for reviewing my project
